export interface Service {
  id: string
  title: string
  slug: string
  description: string
  longDescription: string
  image: string
  features: string[]
  benefits: string[]
  process: string[]
  caseStudy?: {
    title: string
    challenge: string
    solution: string
    results: string[]
  }
}

export const services: Service[] = [
  {
    id: "store-operations",
    title: "Store Operations",
    slug: "store-operations",
    description: "Optimize your retail operations for maximum efficiency and customer satisfaction.",
    longDescription:
      "Our comprehensive store operations consulting helps retailers streamline their daily operations, improve customer experience, and maximize profitability through proven methodologies and best practices.",
    image: "/images/services/store-operations.jpg",
    features: [
      "Store Display Layout Plan",
      "Visual Merchandising",
      "Staff Scheduling Optimization",
      "Customer Service Excellence",
      "Loss Prevention Strategies",
      "Store Performance Analytics",
    ],
    benefits: [
      "Increased operational efficiency",
      "Enhanced customer experience",
      "Reduced operational costs",
      "Improved staff productivity",
      "Better inventory turnover",
      "Higher customer satisfaction scores",
    ],
    process: [
      "Current operations assessment",
      "Gap analysis and recommendations",
      "Implementation planning",
      "Staff training and development",
      "Performance monitoring",
      "Continuous improvement",
    ],
    caseStudy: {
      title: "Fashion Retailer Transformation",
      challenge: "A mid-size fashion retailer was struggling with inconsistent store layouts and declining sales.",
      solution: "We implemented standardized visual merchandising guidelines and optimized store layouts.",
      results: [
        "25% increase in sales per square foot",
        "40% improvement in customer dwell time",
        "30% reduction in inventory shrinkage",
      ],
    },
  },
  {
    id: "digital-transformation",
    title: "Digital Transformation",
    slug: "digital-transformation",
    description: "Transform your retail business with cutting-edge digital solutions and technologies.",
    longDescription:
      "Navigate the digital landscape with confidence. Our digital transformation services help traditional retailers embrace technology to enhance customer experience, streamline operations, and drive growth in the digital age.",
    image: "/images/services/digital-transformation.jpg",
    features: [
      "E-commerce Platform Development",
      "Mobile App Solutions",
      "POS System Integration",
      "Customer Data Analytics",
      "Digital Marketing Strategy",
      "Omnichannel Experience Design",
    ],
    benefits: [
      "Expanded market reach",
      "Improved customer insights",
      "Streamlined operations",
      "Enhanced customer engagement",
      "Increased revenue streams",
      "Future-ready business model",
    ],
    process: [
      "Digital readiness assessment",
      "Technology roadmap development",
      "Platform selection and integration",
      "Staff training and change management",
      "Launch and optimization",
      "Performance monitoring and scaling",
    ],
  },
  {
    id: "franchise-development",
    title: "Franchise Development",
    slug: "franchise-development",
    description: "Scale your retail concept through strategic franchise development and management.",
    longDescription:
      "Expand your successful retail concept through franchising. We provide end-to-end franchise development services, from initial concept validation to ongoing franchisee support and brand management.",
    image: "/images/services/franchise-development.jpg",
    features: [
      "Franchise Business Model Development",
      "Legal Documentation & Compliance",
      "Brand Negotiations",
      "Franchisee Recruitment & Selection",
      "Operations Manual Creation",
      "Ongoing Support Systems",
    ],
    benefits: [
      "Rapid market expansion",
      "Reduced capital requirements",
      "Shared operational risks",
      "Increased brand presence",
      "Recurring revenue streams",
      "Local market expertise",
    ],
    process: [
      "Franchise feasibility analysis",
      "Business model optimization",
      "Legal structure development",
      "Marketing and recruitment",
      "Franchisee onboarding",
      "Ongoing support and monitoring",
    ],
  },
  {
    id: "performance-optimization",
    title: "Performance Optimization",
    slug: "performance-optimization",
    description: "Maximize your retail performance through data-driven insights and strategic improvements.",
    longDescription:
      "Unlock your retail potential with our comprehensive performance optimization services. We analyze every aspect of your business to identify opportunities for improvement and implement strategies that drive measurable results.",
    image: "/images/services/performance-optimization.jpg",
    features: [
      "KPI Development & Tracking",
      "Sales Performance Analysis",
      "Operational Efficiency Audits",
      "Customer Journey Optimization",
      "Profit Margin Enhancement",
      "Competitive Benchmarking",
    ],
    benefits: [
      "Increased profitability",
      "Better decision making",
      "Improved operational efficiency",
      "Enhanced customer satisfaction",
      "Competitive advantage",
      "Sustainable growth",
    ],
    process: [
      "Performance baseline assessment",
      "Data collection and analysis",
      "Opportunity identification",
      "Strategy development",
      "Implementation support",
      "Results monitoring and optimization",
    ],
  },
  {
    id: "risk-management",
    title: "Risk Management",
    slug: "risk-management",
    description: "Protect your retail business with comprehensive risk assessment and mitigation strategies.",
    longDescription:
      "Safeguard your retail operations against various risks with our comprehensive risk management solutions. We help identify, assess, and mitigate risks to ensure business continuity and protect your investments.",
    image: "/images/services/risk-management.jpg",
    features: [
      "Risk Assessment & Analysis",
      "Business Continuity Planning",
      "Insurance Strategy Development",
      "Compliance Management",
      "Crisis Management Protocols",
      "Security System Implementation",
    ],
    benefits: [
      "Reduced business risks",
      "Improved compliance",
      "Enhanced security",
      "Business continuity assurance",
      "Cost-effective risk mitigation",
      "Peace of mind",
    ],
    process: [
      "Risk identification and assessment",
      "Risk prioritization and analysis",
      "Mitigation strategy development",
      "Implementation planning",
      "Monitoring and review",
      "Continuous improvement",
    ],
  },
  {
    id: "skill-academy",
    title: "Skill Academy",
    slug: "skill-academy",
    description: "Empower your team with world-class retail training and development programs.",
    longDescription:
      "Invest in your most valuable asset - your people. Our Skill Academy offers comprehensive training programs designed to enhance retail skills, improve performance, and drive career development across all levels of your organization.",
    image: "/images/services/skill-academy.jpg",
    features: [
      "Customer Service Excellence Training",
      "Sales Techniques & Upselling",
      "Visual Merchandising Workshops",
      "Leadership Development Programs",
      "Product Knowledge Training",
      "Digital Skills Development",
    ],
    benefits: [
      "Improved staff performance",
      "Higher customer satisfaction",
      "Increased sales conversion",
      "Better employee retention",
      "Enhanced brand reputation",
      "Competitive advantage",
    ],
    process: [
      "Training needs assessment",
      "Customized curriculum development",
      "Interactive training delivery",
      "Skills assessment and certification",
      "Performance tracking",
      "Ongoing development support",
    ],
  },
  {
    id: "branding-identity",
    title: "Branding & Identity",
    slug: "branding-identity",
    description: "Create a compelling brand identity that resonates with your target audience.",
    longDescription:
      "Build a strong, memorable brand that stands out in the competitive retail landscape. Our branding and identity services help you develop a cohesive brand strategy that connects with customers and drives loyalty.",
    image: "/images/services/branding-identity.jpg",
    features: [
      "Brand Strategy Development",
      "Visual Identity Design",
      "Brand Guidelines Creation",
      "Store Design & Atmosphere",
      "Marketing Collateral Design",
      "Brand Experience Optimization",
    ],
    benefits: [
      "Strong brand recognition",
      "Increased customer loyalty",
      "Premium pricing opportunities",
      "Consistent brand experience",
      "Competitive differentiation",
      "Enhanced market position",
    ],
    process: [
      "Brand discovery and research",
      "Strategy development",
      "Creative concept development",
      "Design and implementation",
      "Brand launch and rollout",
      "Brand monitoring and evolution",
    ],
  },
  {
    id: "retail-business-intelligence",
    title: "Retail Business Intelligence",
    slug: "retail-business-intelligence",
    description: "Harness the power of data to make informed business decisions and drive growth.",
    longDescription:
      "Transform your data into actionable insights with our retail business intelligence solutions. We help you collect, analyze, and interpret data to make informed decisions that drive growth and improve performance.",
    image: "/images/services/retail-business-intelligence.jpg",
    features: [
      "Data Analytics & Reporting",
      "Customer Behavior Analysis",
      "Sales Forecasting",
      "Inventory Analytics",
      "Market Trend Analysis",
      "Performance Dashboards",
    ],
    benefits: [
      "Data-driven decision making",
      "Improved forecasting accuracy",
      "Better inventory management",
      "Enhanced customer insights",
      "Increased operational efficiency",
      "Competitive advantage",
    ],
    process: [
      "Data audit and assessment",
      "Analytics platform setup",
      "Dashboard development",
      "Training and implementation",
      "Ongoing analysis and insights",
      "Continuous optimization",
    ],
  },
  {
    id: "customer-experience",
    title: "Customer Experience",
    slug: "customer-experience",
    description: "Design exceptional customer experiences that drive loyalty and increase lifetime value.",
    longDescription:
      "Create memorable customer experiences that differentiate your brand and drive loyalty. Our customer experience services help you understand your customers' needs and design touchpoints that exceed expectations.",
    image: "/images/services/customer-experience.jpg",
    features: [
      "Customer Journey Mapping",
      "Touchpoint Optimization",
      "Service Design",
      "Customer Feedback Systems",
      "Loyalty Program Development",
      "Personalization Strategies",
    ],
    benefits: [
      "Increased customer satisfaction",
      "Higher customer retention",
      "Improved brand loyalty",
      "Increased customer lifetime value",
      "Positive word-of-mouth marketing",
      "Competitive differentiation",
    ],
    process: [
      "Customer research and analysis",
      "Journey mapping and gap analysis",
      "Experience design and optimization",
      "Implementation and training",
      "Performance monitoring",
      "Continuous improvement",
    ],
  },
  {
    id: "market-entry-strategy",
    title: "Market Entry Strategy",
    slug: "market-entry-strategy",
    description: "Successfully enter new markets with strategic planning and local market expertise.",
    longDescription:
      "Expand into new markets with confidence. Our market entry strategy services provide comprehensive analysis, strategic planning, and implementation support to ensure successful market penetration and sustainable growth.",
    image: "/images/services/market-entry-strategy.jpg",
    features: [
      "Market Research & Analysis",
      "Competitive Landscape Assessment",
      "Entry Strategy Development",
      "Local Partnership Facilitation",
      "Regulatory Compliance Guidance",
      "Launch Planning & Execution",
    ],
    benefits: [
      "Reduced market entry risks",
      "Faster market penetration",
      "Local market insights",
      "Strategic partnerships",
      "Regulatory compliance",
      "Sustainable growth foundation",
    ],
    process: [
      "Market opportunity assessment",
      "Entry strategy development",
      "Partner identification and evaluation",
      "Implementation planning",
      "Launch execution",
      "Performance monitoring and optimization",
    ],
  },
  {
    id: "international-expansion",
    title: "International Expansion",
    slug: "international-expansion",
    description: "Scale your retail business globally with expert guidance and strategic support.",
    longDescription:
      "Take your retail business global with our international expansion services. We provide end-to-end support for retailers looking to expand internationally, from market selection to operational setup and ongoing management.",
    image: "/images/services/international-expansion.jpg",
    features: [
      "Global Market Assessment",
      "Cultural Adaptation Strategies",
      "International Business Setup",
      "Cross-border Operations",
      "Global Supply Chain Management",
      "Multi-market Brand Management",
    ],
    benefits: [
      "Global market access",
      "Diversified revenue streams",
      "Reduced market dependency",
      "Enhanced brand recognition",
      "Economies of scale",
      "Competitive advantage",
    ],
    process: [
      "Global opportunity assessment",
      "Market prioritization and selection",
      "Entry strategy development",
      "Operational setup and launch",
      "Performance monitoring",
      "Scaling and optimization",
    ],
  },
  {
    id: "visual-merchandising",
    title: "Visual Merchandising",
    slug: "visual-merchandising",
    description: "Create compelling visual displays that attract customers and drive sales.",
    longDescription:
      "Transform your retail space into a compelling shopping destination with our visual merchandising expertise. We help you create displays that not only attract customers but also guide them through an engaging shopping journey that drives sales.",
    image: "/images/services/visual-merchandising.jpg",
    features: [
      "Store Layout Optimization",
      "Window Display Design",
      "Product Presentation Strategies",
      "Seasonal Campaign Development",
      "Brand Storytelling Through Visuals",
      "Staff Training on VM Principles",
    ],
    benefits: [
      "Increased foot traffic",
      "Higher conversion rates",
      "Improved average transaction value",
      "Enhanced brand perception",
      "Better product visibility",
      "Memorable shopping experience",
    ],
    process: [
      "Store assessment and analysis",
      "Visual merchandising strategy development",
      "Design concept creation",
      "Implementation and installation",
      "Staff training and guidelines",
      "Performance monitoring and optimization",
    ],
  },
  {
    id: "ai-retail-analytics",
    title: "AI Retail Analytics",
    slug: "ai-retail-analytics",
    description: "Leverage artificial intelligence to gain deeper insights and automate decision-making.",
    longDescription:
      "Harness the power of artificial intelligence to transform your retail operations. Our AI retail analytics solutions provide advanced insights, predictive capabilities, and automated decision-making tools that give you a competitive edge.",
    image: "/images/services/ai-retail-analytics.jpg",
    features: [
      "Predictive Analytics",
      "Customer Behavior AI",
      "Inventory Optimization AI",
      "Price Optimization Algorithms",
      "Demand Forecasting",
      "Automated Reporting Systems",
    ],
    benefits: [
      "Improved forecasting accuracy",
      "Automated decision making",
      "Enhanced customer insights",
      "Optimized inventory levels",
      "Dynamic pricing capabilities",
      "Reduced operational costs",
    ],
    process: [
      "Data infrastructure assessment",
      "AI solution design and development",
      "Model training and validation",
      "System integration and deployment",
      "Performance monitoring",
      "Continuous model improvement",
    ],
  },
  {
    id: "retail-software-solutions",
    title: "Retail Software Solutions",
    slug: "retail-software-solutions",
    description: "Custom software solutions designed specifically for retail operations and management.",
    longDescription:
      "Streamline your retail operations with custom software solutions tailored to your specific needs. From point-of-sale systems to inventory management and customer relationship management, we develop solutions that integrate seamlessly with your business processes.",
    image: "/images/services/retail-software-solutions.jpg",
    features: [
      "Custom POS Systems",
      "Inventory Management Software",
      "Customer Relationship Management",
      "E-commerce Platform Development",
      "Mobile App Development",
      "System Integration Services",
    ],
    benefits: [
      "Streamlined operations",
      "Improved efficiency",
      "Better data management",
      "Enhanced customer service",
      "Scalable solutions",
      "Competitive advantage",
    ],
    process: [
      "Requirements analysis",
      "Solution design and architecture",
      "Development and testing",
      "Implementation and training",
      "Support and maintenance",
      "Continuous improvement",
    ],
  },
  {
    id: "ecommerce-integration",
    title: "E-commerce Integration",
    slug: "ecommerce-integration",
    description: "Seamlessly integrate online and offline retail channels for a unified customer experience.",
    longDescription:
      "Bridge the gap between your physical and digital retail presence with our e-commerce integration services. We help you create a seamless omnichannel experience that meets customers wherever they are in their shopping journey.",
    image: "/images/services/ecommerce-integration.jpg",
    features: [
      "Omnichannel Strategy Development",
      "Platform Integration",
      "Inventory Synchronization",
      "Order Management Systems",
      "Customer Data Unification",
      "Cross-channel Analytics",
    ],
    benefits: [
      "Unified customer experience",
      "Increased sales opportunities",
      "Better inventory management",
      "Improved customer insights",
      "Enhanced operational efficiency",
      "Competitive advantage",
    ],
    process: [
      "Current system assessment",
      "Integration strategy development",
      "Platform selection and setup",
      "Data migration and synchronization",
      "Testing and optimization",
      "Launch and ongoing support",
    ],
  },
  {
    id: "standard-operating-procedures",
    title: "Standard Operating Procedures",
    slug: "standard-operating-procedures",
    description: "Develop comprehensive SOPs to ensure consistent operations across all locations.",
    longDescription:
      "Establish consistency and efficiency across your retail operations with comprehensive Standard Operating Procedures. We help you document, implement, and maintain SOPs that ensure quality service delivery and operational excellence.",
    image: "/images/services/standard-operating-procedures.jpg",
    features: [
      "Process Documentation",
      "Workflow Optimization",
      "Quality Control Standards",
      "Training Material Development",
      "Compliance Procedures",
      "Performance Monitoring Systems",
    ],
    benefits: [
      "Consistent operations",
      "Improved efficiency",
      "Better quality control",
      "Easier staff training",
      "Regulatory compliance",
      "Scalable operations",
    ],
    process: [
      "Current process analysis",
      "SOP development and documentation",
      "Staff training and implementation",
      "Monitoring and feedback",
      "Continuous improvement",
      "Regular updates and maintenance",
    ],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((service) => service.slug === slug)
}

export function getAllServices(): Service[] {
  return services
}
